local M = {}

--- Get editor UI highlight groups
--- @param c theme.Colors Color palette
--- @return table Highlight groups for editor UI elements
function M.get(c)
	return {
		Added = { fg = c.changes.add.fg },
		Changed = { fg = c.changes.change.fg },
		ColorColumn = { bg = c.color_column },
		Conceal = { fg = c.fg_dim },
		CurSearch = { fg = c.fg, bg = c.match },
		Cursor = { bg = c.cursor },
		CursorColumn = { bg = c.cursorline },
		CursorIM = { bg = c.cursor },
		CursorLine = { bg = c.cursorline },
		CursorLineNr = { fg = c.line_number_current, bg = c.cursorline },
		DiffAdd = { bg = c.changes.add.line_bg },
		DiffChange = { bg = c.changes.change.line_bg },
		-- Native diff uses this for missing-line filler rows.
		DiffDelete = { fg = c.fg_dim, bg = c.bg_gutter },
		DiffText = { bg = c.changes.change.text_bg },
		-- Neovim 0.12+ uses this for insertions inside changed lines.
		DiffTextAdd = { link = "DiffText" },
		Directory = { fg = c.directory },
		ErrorMsg = { fg = c.error },
		FloatBorder = { fg = c.border, bg = c.none },
		FloatTitle = { fg = c.fg, bg = c.bg, bold = true },
		FoldColumn = { fg = c.line_number, bg = c.none },
		Folded = { fg = c.fold_fg, bg = c.fold_bg },
		IncSearch = { fg = c.fg, bg = c.match },
		LineNr = { fg = c.line_number, bg = c.none },
		MatchParen = { bg = c.match, bold = true },
		ModeMsg = { fg = c.ok },
		MoreMsg = { fg = c.info },
		MsgArea = { fg = c.fg, bg = c.none },
		MsgSeparator = { fg = c.border, bg = c.none },
		NonText = { fg = c.fg_dim },
		Normal = { fg = c.fg, bg = c.bg },
		NormalNC = { link = "Normal" },
		NormalFloat = { fg = c.fg, bg = c.none },
		OkMsg = { fg = c.ok },
		Pmenu = { link = "NormalFloat" },
		PmenuBorder = { link = "FloatBorder" },
		PmenuExtra = { fg = c.fg_muted, bg = c.none },
		PmenuKind = { fg = c.type, bg = c.none },
		PmenuMatch = { fg = c.search_match, bg = c.none, bold = true },
		PmenuMatchSel = { link = "PmenuSel" },
		PmenuSbar = { bg = c.none },
		PmenuSel = { link = "Visual" },
		PmenuThumb = { bg = c.border },
		Question = { fg = c.info },
		QuickFixLine = { bg = c.quickfixline },
		Removed = { fg = c.changes.delete.fg },
		Search = { fg = c.fg, bg = c.search },
		SignColumn = { fg = c.line_number, bg = c.none },
		SpecialKey = { fg = c.fg_dim },
		SpellBad = { sp = c.error, undercurl = true },
		SpellCap = { sp = c.warning, undercurl = true },
		SpellLocal = { sp = c.hint, undercurl = true },
		SpellRare = { sp = c.info, undercurl = true },
		StatusLine = { fg = c.fg, bg = c.bg_surface },
		StatusLineNC = { fg = c.fg_dim, bg = c.bg_gutter },
		Substitute = { fg = c.fg, bg = c.match },
		TabLine = {},
		TabLineFill = {},
		TabLineSel = { link = "Visual" },
		Title = { fg = c.func, bold = true },
		VertSplit = { fg = c.border },
		Visual = { bg = c.visual },
		VisualNOS = { bg = c.visual },
		WarningMsg = { fg = c.warning },
		Whitespace = { fg = c.fg_dim },
		WinBar = { fg = c.fg, bg = c.cursorline },
		WinBarNC = { fg = c.fg_muted, bg = c.cursorline },
		WinSeparator = { fg = c.border },
		healthError = { fg = c.error },
		healthSuccess = { fg = c.ok },
		healthWarning = { fg = c.warning },
		lCursor = { bg = c.cursor },
		qfFileName = { link = "Directory" },
		qfLineNr = { link = "LineNr" },
	}
end

return M
