local M = {}

--- Get editor UI highlight groups
--- @param c theme.Colors Color palette
--- @return table Highlight groups for editor UI elements
function M.get(c)
	return {
		Added = { fg = c.git_add },
		Changed = { fg = c.git_change },
		ColorColumn = { bg = c.color_column },
		Conceal = { fg = c.text2 },
		CurSearch = { fg = c.text, bg = c.match },
		Cursor = { bg = c.cursor },
		CursorColumn = { bg = c.cursorline },
		CursorIM = { bg = c.cursor },
		CursorLine = { bg = c.cursorline },
		CursorLineNr = { fg = c.text, bg = c.cursorline },
		DiffAdd = { bg = c.diff_add },
		DiffChange = { bg = c.diff_change },
		DiffDelete = { bg = c.diff_delete },
		DiffText = { bg = c.diff_change },
		Directory = { fg = c.identifier },
		ErrorMsg = { fg = c.error },
		FloatBorder = { fg = c.border, bg = c.none },
		FloatTitle = { fg = c.text, bg = c.none, bold = true },
		FoldColumn = { fg = c.line_number, bg = c.none },
		Folded = { fg = c.text1, bg = c.fold },
		IncSearch = { fg = c.text, bg = c.match },
		LineNr = { fg = c.line_number, bg = c.none },
		MatchParen = { bg = c.match, bold = true },
		MoreMsg = { fg = c.info },
		MsgArea = { fg = c.text, bg = c.none },
		MsgSeparator = { fg = c.border, bg = c.none },
		NonText = { fg = c.text2 },
		Normal = { fg = c.text, bg = c.none },
		NormalFloat = { fg = c.text, bg = c.none },
		Pmenu = { link = "NormalFloat" },
		PmenuBorder = { link = "FloatBorder" },
		PmenuExtra = { fg = c.text1, bg = c.none },
		PmenuKind = { fg = c.type, bg = c.none },
		PmenuMatch = { fg = c.search_match, bg = c.none, bold = true },
		PmenuMatchSel = { link = "PmenuSel" },
		PmenuSbar = { bg = c.none },
		PmenuSel = { link = "Visual" },
		PmenuThumb = { bg = c.border },
		Question = { fg = c.info },
		QuickFixLine = { bg = c.cursorline },
		Removed = { fg = c.git_delete },
		Search = { fg = c.text, bg = c.search },
		SignColumn = { fg = c.line_number, bg = c.none },
		SpecialKey = { fg = c.text2 },
		SpellBad = { sp = c.error, undercurl = true },
		SpellCap = { sp = c.warning, undercurl = true },
		SpellLocal = { sp = c.hint, undercurl = true },
		SpellRare = { sp = c.info, undercurl = true },
		StatusLine = { fg = c.text, bg = c.base2 },
		StatusLineNC = { fg = c.text1, bg = c.base2 },
		Substitute = { fg = c.text, bg = c.match },
		TabLine = {},
		TabLineFill = {},
		TabLineSel = { link = "Visual" },
		Title = { fg = c.func, bold = true },
		VertSplit = { fg = c.border },
		Visual = { bg = c.visual },
		VisualNOS = { bg = c.visual },
		WarningMsg = { fg = c.warning },
		Whitespace = { fg = c.text2 },
		WinBar = { fg = c.text, bg = c.cursorline },
		WinBarNC = { fg = c.text1, bg = c.cursorline },
		WinSeparator = { fg = c.border },
		healthError = { fg = c.error },
		healthSuccess = { fg = c.ok },
		healthWarning = { fg = c.warning },
		lCursor = { bg = c.cursor },
		qfFileName = { fg = c.identifier },
		qfLineNr = { fg = c.line_number },
	}
end

return M
