local M = {}

--- Get LSP highlight groups
--- @return theme.Highlights
function M.get()
	return {
		["@lsp.mod.constant"] = { link = "@constant" },
		["@lsp.mod.defaultLibrary"] = { link = "@lsp.mod.keyword" },
		["@lsp.mod.format"] = { link = "@string.escape" },
		["@lsp.mod.readonly"] = { link = "@lsp.mod.constant" },
		["@lsp.mod.readonly.javascript"] = {},
		["@lsp.mod.readonly.tsx"] = {},
		["@lsp.mod.readonly.typescript"] = {},
		["@lsp.mod.readonly.typescriptreact"] = {},
		["@lsp.mod.static"] = { link = "@lsp.type.function" },
		["@lsp.type.class"] = { link = "@lsp.type.type" },
		["@lsp.type.class.javascript"] = { link = "@type.typescript" },
		["@lsp.type.class.lua"] = { link = "@variable.lua" },
		["@lsp.type.class.tsx"] = { link = "@type.typescript" },
		["@lsp.type.class.typescript"] = { link = "@type.typescript" },
		["@lsp.type.class.typescriptreact"] = { link = "@type.typescript" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.decorator"] = { link = "PreProc" },
		["@lsp.type.decorator.proto"] = { link = "@identifier" },
		["@lsp.type.enum"] = { link = "@lsp.type.type" },
		["@lsp.type.enum.proto"] = { link = "@type.proto" },
		["@lsp.type.enumMember"] = { link = "@property" },
		["@lsp.type.field"] = { link = "@variable.member" },
		["@lsp.type.function"] = {},
		["@lsp.type.interface"] = { link = "@lsp.type.type" },
		["@lsp.type.interface.javascript"] = { link = "@type.typescript" },
		["@lsp.type.interface.proto"] = { link = "@type.proto" },
		["@lsp.type.interface.tsx"] = { link = "@type.typescript" },
		["@lsp.type.interface.typescript"] = { link = "@type.typescript" },
		["@lsp.type.interface.typescriptreact"] = { link = "@type.typescript" },
		["@lsp.type.keyword"] = { link = "@keyword" },
		["@lsp.type.macro"] = { link = "Macro" },
		["@lsp.type.method"] = {},
		["@lsp.type.module"] = { link = "@lsp.type.namespace" },
		["@lsp.type.namespace"] = { link = "@label" },
		["@lsp.type.namespace.proto"] = { link = "@variable.member.proto" },
		["@lsp.type.parameter"] = { link = "@lsp.type.variable" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.property.javascript"] = {},
		["@lsp.type.property.proto"] = { link = "@property.proto" },
		["@lsp.type.string.go"] = {},
		["@lsp.type.struct"] = { link = "@lsp.type.type" },
		["@lsp.type.struct.proto"] = { link = "@type.proto" },
		["@lsp.type.type"] = { link = "@type" },
		["@lsp.type.type.javascript"] = { link = "@type.typescript" },
		["@lsp.type.type.proto"] = { link = "@type.proto" },
		["@lsp.type.type.tsx"] = { link = "@type.typescript" },
		["@lsp.type.type.typescript"] = { link = "@type.typescript" },
		["@lsp.type.type.typescriptreact"] = { link = "@type.typescript" },
		["@lsp.type.typeParameter"] = { link = "@lsp.type.type" },
		["@lsp.type.variable"] = { link = "@variable" },
		["@lsp.typemod.class.declaration"] = { link = "@lsp.typemod.type.definition" },
		["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.function.defaultLibrary.javascript"] = { link = "@function" },
		["@lsp.typemod.function.defaultLibrary.tsx"] = { link = "@function" },
		["@lsp.typemod.function.defaultLibrary.typescript"] = { link = "@function" },
		["@lsp.typemod.function.defaultLibrary.typescriptreact"] = { link = "@function" },
		["@lsp.typemod.interface.declaration"] = { link = "@lsp.typemod.type.definition" },
		["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
		["@lsp.typemod.type.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.type.defaultLibrary.javascript"] = { link = "@type.typescript" },
		["@lsp.typemod.type.defaultLibrary.proto"] = { link = "@type.proto" },
		["@lsp.typemod.type.defaultLibrary.tsx"] = { link = "@type.typescript" },
		["@lsp.typemod.type.defaultLibrary.typescript"] = { link = "@type.typescript" },
		["@lsp.typemod.type.defaultLibrary.typescriptreact"] = { link = "@type.typescript" },
		["@lsp.typemod.type.definition"] = { link = "@type.definition" },
		["@lsp.typemod.variable.constant"] = { link = "@lsp.mod.constant" },
		["@lsp.typemod.variable.defaultLibrary"] = { link = "@type.builtin" },
		["@lsp.typemod.variable.defaultLibrary.javascript"] = { link = "@variable.builtin.typescript" },
		["@lsp.typemod.variable.defaultLibrary.tsx"] = { link = "@variable.builtin.typescript" },
		["@lsp.typemod.variable.defaultLibrary.typescript"] = { link = "@variable.builtin.typescript" },
		["@lsp.typemod.variable.defaultLibrary.typescriptreact"] = { link = "@variable.builtin.typescript" },
		["@lsp.typemod.variable.readonly"] = { link = "@lsp.mod.constant" },
		["@lsp.typemod.variable.readonly.go"] = {},
		["@lsp.typemod.variable.readonly.javascript"] = { link = "@constant.typescript" },
		["@lsp.typemod.variable.readonly.tsx"] = { link = "@constant.typescript" },
		["@lsp.typemod.variable.readonly.typescript"] = { link = "@constant.typescript" },
		["@lsp.typemod.variable.readonly.typescriptreact"] = { link = "@constant.typescript" },
	}
end

return M
