local M = {}

--- Get Treesitter highlights
--- @param c theme.Colors Color palette
--- @param config theme.Config Theme configuration
--- @return theme.Highlights
function M.get(c, config)
	local util = require("islands-dark.util")
	local styles = util.get_styles(config)

	local base = {
		["@annotation"] = { link = "PreProc" },
		["@attribute"] = { link = "PreProc" },
		["@boolean"] = { link = "Boolean" },
		["@character"] = { link = "Character" },
		["@character.special"] = { link = "SpecialChar" },
		["@comment"] = styles.comments({ link = "Comment" }),
		["@comment.error"] = styles.comments({ link = "Error" }),
		["@comment.hint"] = styles.comments({ fg = c.hint }),
		["@comment.info"] = styles.comments({ fg = c.info }),
		["@comment.note"] = styles.comments({ fg = c.hint }),
		["@comment.todo"] = styles.comments({ link = "Todo" }),
		["@comment.warning"] = styles.comments({ link = "Debug" }),
		["@conceal.markdown_inline"] = { fg = c.keyword },
		["@constant"] = { link = "Constant" },
		["@constant.bash"] = { fg = c.variable },
		["@constant.builtin"] = { fg = c.constant_builtin },
		["@constructor"] = { link = "Function" },
		["@diff.delta"] = { link = "DiffChange" },
		["@diff.minus"] = { link = "DiffDelete" },
		["@diff.plus"] = { link = "DiffAdd" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = styles.functions({ fg = c.func_builtin }),
		["@function.call"] = styles.functions({ fg = c.func_call }),
		["@function.macro"] = { link = "Macro" },
		["@function.method"] = { link = "Function" },
		["@function.method.call"] = { link = "@function.call" },
		["@keyword"] = { link = "Keyword" },
		["@keyword.conditional.ternary"] = { link = "Operator" },
		["@keyword.exception"] = { link = "Exception" },
		["@label"] = { link = "Label" },
		["@label.markdown"] = { fg = c.constant },
		["@label.yaml"] = { link = "Tag" },
		["@markup.heading"] = {},
		["@markup.heading.1.markdown"] = { fg = c.constant },
		["@markup.heading.2.markdown"] = { link = "@markup.heading.1.markdown" },
		["@markup.heading.3.markdown"] = { link = "@markup.heading.1.markdown" },
		["@markup.heading.4.markdown"] = { link = "@markup.heading.1.markdown" },
		["@markup.heading.5.markdown"] = { link = "@markup.heading.1.markdown" },
		["@markup.heading.6.markdown"] = { link = "@markup.heading.1.markdown" },
		["@markup.italic"] = { italic = true },
		["@markup.link"] = { link = "Underlined" },
		["@markup.link.label"] = { link = "@markup.link" },
		["@markup.link.url"] = { link = "@markup.link" },
		["@markup.link.url.markdown_inline"] = { fg = c.link, italic = true },
		["@markup.list"] = { fg = c.keyword },
		["@markup.list.checked"] = { fg = c.text },
		["@markup.list.unchecked"] = { fg = c.text },
		["@markup.math"] = { link = "Number" },
		["@markup.quote"] = { link = "Keyword" },
		["@markup.quote.markdown"] = { fg = c.string },
		["@markup.raw"] = { fg = c.string },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.strong"] = { bold = true },
		["@markup.underline"] = { underline = true },
		["@module"] = { link = "Include" },
		["@module.builtin"] = { fg = c.keyword },
		["@none"] = {},
		["@number"] = { link = "Number" },
		["@operator"] = { link = "Operator" },
		["@parameter"] = { link = "@variable" },
		["@parameter.builtin"] = { link = "@variable" },
		["@property"] = { fg = c.property },
		["@punctuation"] = { link = "Delimiter" },
		["@punctuation.special.markdown"] = { fg = c.keyword },
		["@string"] = { link = "String" },
		["@string.documentation"] = { link = "SpecialComment" },
		["@string.escape"] = { fg = c.escape },
		["@string.regexp"] = { fg = c.regex },
		["@string.special"] = { link = "SpecialChar" },
		["@string.special.symbol"] = { fg = c.constant },
		["@string.special.url"] = { link = "Underlined" },
		["@tag"] = { link = "Tag" },
		["@tag.attribute"] = { fg = c.attribute },
		["@tag.delimiter"] = { link = "Tag" },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = c.type_builtin },
		["@type.definition"] = { link = "Typedef" },
		["@type.qualifier"] = { link = "Keyword" },
		["@type.sql"] = { fg = c.text },
		["@variable"] = { link = "Identifier" },
		["@variable.builtin"] = { fg = c.variable_builtin },
		["@variable.member"] = { link = "@property" },
	}

	return vim.tbl_deep_extend("force", base, M.get_langs(c, styles))
end

--- Get language-specific Treesitter highlights
--- @param c theme.Colors Color palette
--- @param styles theme.Styles Styles configuration
--- @return theme.Highlights
function M.get_langs(c, styles)
	return {
		["@constant.builtin.php"] = { link = "Constant" },
		["@constant.builtin.xml"] = { link = "Special" },
		["@constant.css"] = { link = "Tag" },
		["@constant.html"] = { link = "Tag" },
		["@constant.javascript"] = { link = "@constant.typescript" },
		["@constant.terraform"] = { fg = c.keyword },
		["@constant.typescript"] = { fg = c.variable },
		["@constant.typescriptreact"] = { link = "@constant.typescript" },
		["@constructor.go"] = { link = "@function.call" },
		["@constructor.javascript"] = { link = "Keyword" },
		["@constructor.lua"] = { fg = c.braces },
		["@constructor.php"] = { fg = c.variable },
		["@constructor.python"] = { link = "Keyword" },
		["@constructor.tsx"] = { link = "@constructor.typescript" },
		["@constructor.typescript"] = { link = "Keyword" },
		["@constructor.typescriptreact"] = { link = "@constructor.typescript" },
		["@function.builtin.bash"] = { link = "Keyword" },
		["@function.call.javascript"] = { link = "@function.call.typescript" },
		["@function.call.php"] = { link = "Function" },
		["@function.call.tsx"] = { link = "@function.call.typescript" },
		["@function.call.typescript"] = { link = "Function" },
		["@function.call.typescriptreact"] = { link = "@function.call.typescript" },
		["@function.method.call.javascript"] = { link = "Function" },
		["@function.method.call.php"] = { link = "Function" },
		["@function.method.call.tsx"] = { link = "Function" },
		["@function.method.call.typescript"] = { link = "Function" },
		["@function.method.call.typescriptreact"] = { link = "Function" },
		["@keyword.directive.define.xml"] = { link = "Tag" },
		["@keyword.directive.xml"] = { link = "Tag" },
		["@module.php"] = { fg = c.variable },
		["@number.xml"] = { link = "String" },
		["@property.go"] = { fg = c.variable },
		["@property.proto"] = { fg = c.variable },
		["@property.yaml"] = { link = "Keyword" },
		["@punctuation.delimiter.css"] = { link = "@tag.css" },
		["@punctuation.special.yaml"] = { fg = c.text },
		["@string.special.url.gomod"] = { link = "String" },
		["@string.special.url.gosum"] = { link = "String" },
		["@string.special.xml"] = { link = "String" },
		["@tag.builtin.tsx"] = { link = "Tag" },
		["@tag.css"] = { link = "Tag" },
		["@tag.delimiter.tsx"] = { link = "Tag" },
		["@type.javascript"] = { link = "@type.typescript" },
		["@type.parameter.javascript"] = { fg = c.type_parameter },
		["@type.parameter.tsx"] = { fg = c.type_parameter },
		["@type.parameter.typescript"] = { fg = c.type_parameter },
		["@type.parameter.typescriptreact"] = { fg = c.type_parameter },
		["@type.php"] = { fg = c.variable },
		["@type.phpdoc"] = { link = "@type.php" },
		["@type.proto"] = { link = "@identifier" },
		["@type.terraform"] = { fg = c.identifier },
		["@type.tsx"] = { link = "@type.typescript" },
		["@type.typescript"] = { fg = c.variable },
		["@type.typescriptreact"] = { link = "@type.typescript" },
		["@type.yaml"] = { link = "Tag" },
		["@variable.member.go"] = { link = "@property.go" },
		["@variable.member.proto"] = { link = "@variable" },
		["@variable.member.python"] = { link = "@variable" },
		["@variable.php"] = styles.variables({ fg = c.constant }),
	}
end

return M
